name: Validate JSON files

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  validate-json:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14' 

    - name: Install jsonlint
      run: npm install -g jsonlint

    - name: Validate JSON files
      run: |
        jsonlint -q translations/**/*.json 
